#!/bin/bash

echo 'Brew update && upgrade'
brew update && brew upgrade

echo 'Starting docker machine'
docker-machine start default

eval $(docker-machine env default)

echo -e "\033[32mGood Morning Albert !\033[0m"
