# Path to your oh-my-zsh installation.
source $ZSH/oh-my-zsh.sh

source ~/config/zsh/alias

export MAIL42=ale-batt@student.42.fr
export USER42=ale-batt

export ZSH_THEME="agnoster"
export DEFAULT_USER="aera_style"

# Oh-my-zsh plugin list
export ZSH=$HOME/.oh-my-zsh
plugins=(git ruby sublime zsh-syntax-highlighting alias-tips)

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"

# Pour GVM
export GOPATH="$HOME/golang"

eval $(docker-machine env default)
eval $(thefuck --alias)

